package io.goldstone.blockchain.common.value

/**
 * @date 26/03/2018 1:03 AM
 * @author KaySaith
 */
object ArgumentKey {
	
	const val walletSettingsTitle = "walletSettingsTitle"
	const val profileTitle = "profileTitle"
	const val mnemonicCode = "mnemonicCode"
	const val walletAddress = "walletAddress"
	const val transactionDetail = "transactionDetail"
	const val transactionFromList = "transactionFromList"
	const val tokenDetail = "tokenDetail"
	const val paymentAddress = "paymentAddress"
	const val paymentCount = "count"
	const val tokenModel = "tokenModel"
	const val webViewUrl = "webViewUrl"
	const val webViewName = "webViewName"
	const val notificationTransaction = "notificationTransaction"
	const val quotationOverlayTitle = "quotationOverlay"
	const val quotationOverlayInfo = "quotationCurrencyInfo"
	const val quotationCurrencyDetail = "quotationCurrencyDetail"
	const val gasEditor = "gasEditor"
	const val gasSize = "gasSize"
	const val isBTCSeries = "isBTCSeries"
	const val gasPrepareModel = "gasPrepareModel"
	const val btcSeriesPrepareModel = "btcseriesPrepareModel"
	const val fromQuickTransfer = "fromQuickTransfer"
	const val fromQuickDeposit = "fromQuickDeposit"
	const val isMainnet = "isMainnet"
	const val addressModel = "addressModel"
	const val address = "address"
	const val chainType = "chainType"
	const val coinType = "coinType"
	const val defaultEOSAccountName = "defaultEOSAccountName"
	const val contact = "contact"
	const val eosAccountRegister = "eosAccountRegister"
}

object IntentKey {
	const val hashFromNotify = "hashFromNotify"
}

object SharesPreference {
	const val registerPush = "registerPush"
	const val rate = "rate"
	const val currencyCode = "currencyCode"
	const val currentChain = "currentChain"
	const val currentChainName = "currentChainName"
	const val etcCurrentChain = "etcCurrentChain"
	const val ltcCurrentChain = "ltcCurrentChain"
	const val bchCurrentChain = "bchCurrentChain"
	const val eosCurrentChain = "eosCurrentChain"
	const val btcCurrentChain = "btcCurrentChain"
	const val etcCurrentChainName = "etcCurrentChainName"
	const val ltcCurrentChainName = "ltcCurrentChainName"
	const val bchCurrentChainName = "bchCurrentChainName"
	const val eosCurrentChainName = "eosCurrentChainName"
	const val btcCurrentChainName = "btcCurrentChainName"
	const val currentLanguage = "currentLanguage"
	const val walletCount = "walletCount"
	const val maxWalletID = "maxWalletID"
	const val walletType = "walletType"
	const val goldStoneID = "goldStoneID"
	const val unregisterGoldStoneID = "unregisterGoldStoneID"
	const val activityIsResult = "activityIsResult"
	const val currentEthereumAddress = "currentEthereumAddress"
	const val currentEOSName= "currentEOSName"
	const val currentETCAddress = "currentETCAddress"
	const val currentEOSAddress = "currentEOSAddress"
	const val currentLTCAddress = "currentLTCAddress"
	const val currentBCHAddress = "currentBCHAddress"
	const val currentBTCAddress = "currentBTCAddress"
	const val currentBTCTestAddress = "currentBTCTestAddress"
	const val currentName = "currentName"
	const val currentBalance = "currentBalance"
	const val currentID = "currentID"
	const val currentIsWatchOrNot = "currentIsWatchOrNot"
	const val isNotchScreen = "isNotchScreen"
	const val isEncryptERCNodeRequest = "isEncryptERCNodeRequest"
	const val isEncryptETCNodeRequest = "isEncryptETCNodeRequest"
	const val isTestEnvironment = "isTestEnvironment"
	const val yingYongBaoInReview = "yingYongBaoInReview"
}